
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - image: spring-petclinic
        name: spring-petclinic
        ports:
          - name: http
            containerPort: 8080
        envFrom: 
          - configMapRef: 
              name:  runtime-env  