
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
      - name: spring-petclinic
        image: spring-petclinic
        ports:
          - name: http
            containerPort: 8080        
        env:
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db.password       
        envFrom: 
          - configMapRef: 
              name:  runtime-env-cm