apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: spring-petclinic-dev
configMapGenerator:
- name: runtime-env
  behavior: create
  # options:
  #   disableNameSuffixHash: true
  literals:
    - RUNTIME_ENV=dev
namePrefix: dev-
namespace: dev-spring-petclinic
images:
- name: spring-petclinic
  newName: docker.io/andriykalashnykov/spring-petclinic
  newTag: "1.2"
