apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: spring-petclinic-prod
# namePrefix: prod-  
images:
- name: docker.io/andriykalashnykov/spring-petclinic
  newTag: "1.1"
