apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: spring-petclinic-prod
configMapGenerator:
- name: runtime-env-cm
  behavior: create
  # options:
  #   disableNameSuffixHash: true
  literals:
    - RUNTIME_ENV=prod
secretGenerator:
  # options:
  #   disableNameSuffixHash: true
- literals:
  - db-password=6789
  name: db-secret
  type: Opaque  
namePrefix: prod-
namespace: prod-spring-petclinic
images:
- name: spring-petclinic
  newName: docker.io/andriykalashnykov/spring-petclinic
  newTag: "1.1"
patchesStrategicMerge:
  - deployment.yaml