apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
commonLabels:
  app: spring-petclinic-prod
configMapGenerator:
- name: runtime-env
  behavior: create
  # options:
  #   disableNameSuffixHash: true
  literals:
    - RUNTIME_ENV=PROD  
namePrefix: prod-
namespace: prod-spring-petclinic
images:
- name: spring-petclinic
  newName: docker.io/andriykalashnykov/spring-petclinic
  newTag: "1.1"
patchesStrategicMerge:
  - deployment.yaml